name: Azure Web App Deploy

on:
  push:
    branches:
      - main
    paths:
     - 'Back/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'KHTML-dku'          # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './Back/oti/build/libs/'  # set this to the path to your JAR file (e.g., 'build/libs/')
  JAVA_VERSION: '21'                        # set this to the Java version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./Back/oti

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ./Back/oti

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}oti-0.0.1-SNAPSHOT.jar
